FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /build
ENV MAVEN_OPTS="-Xmx512m"

# maven aliyun mirror
COPY docker/maven/settings.xml /root/.m2/settings.xml
COPY pom.xml .
COPY bil-common ./bil-common
COPY bil-admin ./bil-admin
COPY bil-auth ./bil-auth
COPY bil-comment ./bil-comment
COPY bil-gateway ./bil-gateway
COPY bil-interaction ./bil-interaction
COPY bil-user ./bil-user
COPY bil-video ./bil-video

RUN mvn -pl bil-gateway -am clean package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /build/bil-gateway/target/bil-gateway-1.0.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-Xmx512m", "-jar", "app.jar"]
