server:
  port: 7076
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bilisql?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.5.131
    port: 6379
    database: 0
    timeout: 2000
  elasticsearch:
    uris: http://192.168.5.131:9200
    connection-timeout: 3s
    socket-timeout: 5s
elasticsearch:
  enabled: true
project:
  folder: D:/BilBil/bilweb
  video:
    upload-temp: D:/BilBil/bilweb/temp
    output: D:/BilBil/bilweb/videos
seata:
  enabled: true
  application-id: bil-user
  tx-service-group: bil-user-seata-service-group
  service:
    vgroup-mapping:
      bil-user-seata-service-group: default
    grouplist:
      default: 192.168.5.131:8091
sentinel:
  eager: true
  transport:
    dashboard: 192.168.5.131:8089
    port: 8726
